- name : Configure Webserver with nginx
  hosts: webservers
  sudo: True
  tasks:
    - name: install nginx
      yum: name=nginx

    - name: copy index.html
      template: src=template/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644

    - name: restart nginx
      service: name=nginx state=restarted
